// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contracts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertContract = `-- name: InsertContract :one
INSERT INTO contracts (
    game_id,
    payload_json,
    status
) VALUES (
    $1, $2, $3
)
RETURNING id, game_id, payload_json, status, accepted_at, delivered_at
`

type InsertContractParams struct {
	GameID      uuid.UUID       `json:"game_id"`
	PayloadJson json.RawMessage `json:"payload_json"`
	Status      string          `json:"status"`
}

func (q *Queries) InsertContract(ctx context.Context, arg InsertContractParams) (Contract, error) {
	row := q.db.QueryRow(ctx, insertContract, arg.GameID, arg.PayloadJson, arg.Status)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PayloadJson,
		&i.Status,
		&i.AcceptedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const listContractsByGame = `-- name: ListContractsByGame :many
SELECT id, game_id, payload_json, status, accepted_at, delivered_at FROM contracts
WHERE game_id = $1
ORDER BY id
`

func (q *Queries) ListContractsByGame(ctx context.Context, gameID uuid.UUID) ([]Contract, error) {
	rows, err := q.db.Query(ctx, listContractsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contract
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PayloadJson,
			&i.Status,
			&i.AcceptedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContractStatus = `-- name: UpdateContractStatus :one
UPDATE contracts
SET
    status = $2,
    accepted_at = $3,
    delivered_at = $4
WHERE id = $1
RETURNING id, game_id, payload_json, status, accepted_at, delivered_at
`

type UpdateContractStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) UpdateContractStatus(ctx context.Context, arg UpdateContractStatusParams) (Contract, error) {
	row := q.db.QueryRow(ctx, updateContractStatus,
		arg.ID,
		arg.Status,
		arg.AcceptedAt,
		arg.DeliveredAt,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PayloadJson,
		&i.Status,
		&i.AcceptedAt,
		&i.DeliveredAt,
	)
	return i, err
}
