// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertEvents implements pgx.CopyFromSource.
type iteratorForInsertEvents struct {
	rows                 []InsertEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].GameID,
		r.rows[0].T,
		r.rows[0].Kind,
		r.rows[0].PayloadJson,
	}, nil
}

func (r iteratorForInsertEvents) Err() error {
	return nil
}

func (q *Queries) InsertEvents(ctx context.Context, arg []InsertEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"game_events"}, []string{"game_id", "t", "kind", "payload_json"}, &iteratorForInsertEvents{rows: arg})
}
