// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertEvent = `-- name: InsertEvent :one
INSERT INTO game_events (
    game_id,
    t,
    kind,
    payload_json
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, game_id, t, kind, payload_json, created_at
`

type InsertEventParams struct {
	GameID      uuid.UUID `json:"game_id"`
	T           float64   `json:"t"`
	Kind        string    `json:"kind"`
	PayloadJson []byte    `json:"payload_json"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (GameEvent, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.GameID,
		arg.T,
		arg.Kind,
		arg.PayloadJson,
	)
	var i GameEvent
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.T,
		&i.Kind,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

type InsertEventsParams struct {
	GameID      uuid.UUID `json:"game_id"`
	T           float64   `json:"t"`
	Kind        string    `json:"kind"`
	PayloadJson []byte    `json:"payload_json"`
}

const listEventsByGame = `-- name: ListEventsByGame :many
SELECT id, game_id, t, kind, payload_json, created_at FROM game_events
WHERE game_id = $1
ORDER BY t ASC, id ASC
`

func (q *Queries) ListEventsByGame(ctx context.Context, gameID uuid.UUID) ([]GameEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameEvent
	for rows.Next() {
		var i GameEvent
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.T,
			&i.Kind,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
