// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: games.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (
    seed,
    status,
    map_json,
    crisis,
    terminator_json,
    rover_type
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, seed, status, map_json, crisis, terminator_json, colony_score, earth_score, rover_type, created_at, finished_at
`

type CreateGameParams struct {
	Seed           string          `json:"seed"`
	Status         string          `json:"status"`
	MapJson        json.RawMessage `json:"map_json"`
	Crisis         string          `json:"crisis"`
	TerminatorJson json.RawMessage `json:"terminator_json"`
	RoverType      string          `json:"rover_type"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.Seed,
		arg.Status,
		arg.MapJson,
		arg.Crisis,
		arg.TerminatorJson,
		arg.RoverType,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Seed,
		&i.Status,
		&i.MapJson,
		&i.Crisis,
		&i.TerminatorJson,
		&i.ColonyScore,
		&i.EarthScore,
		&i.RoverType,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, seed, status, map_json, crisis, terminator_json, colony_score, earth_score, rover_type, created_at, finished_at FROM games
WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Seed,
		&i.Status,
		&i.MapJson,
		&i.Crisis,
		&i.TerminatorJson,
		&i.ColonyScore,
		&i.EarthScore,
		&i.RoverType,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listGamesBySeed = `-- name: ListGamesBySeed :many
SELECT id, seed, status, map_json, crisis, terminator_json, colony_score, earth_score, rover_type, created_at, finished_at FROM games
WHERE seed = $1
ORDER BY created_at DESC
`

func (q *Queries) ListGamesBySeed(ctx context.Context, seed string) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesBySeed, seed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Seed,
			&i.Status,
			&i.MapJson,
			&i.Crisis,
			&i.TerminatorJson,
			&i.ColonyScore,
			&i.EarthScore,
			&i.RoverType,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGameStatus = `-- name: UpdateGameStatus :one
UPDATE games
SET
    status = $2,
    colony_score = $3,
    earth_score = $4,
    finished_at = $5
WHERE id = $1
RETURNING id, seed, status, map_json, crisis, terminator_json, colony_score, earth_score, rover_type, created_at, finished_at
`

type UpdateGameStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	ColonyScore int32              `json:"colony_score"`
	EarthScore  int32              `json:"earth_score"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGameStatus,
		arg.ID,
		arg.Status,
		arg.ColonyScore,
		arg.EarthScore,
		arg.FinishedAt,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Seed,
		&i.Status,
		&i.MapJson,
		&i.Crisis,
		&i.TerminatorJson,
		&i.ColonyScore,
		&i.EarthScore,
		&i.RoverType,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
