// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ghosts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getGhostBySeed = `-- name: GetGhostBySeed :one
SELECT seed, game_id, colony_score, earth_score, replay_json, updated_at FROM ghost_runs
WHERE seed = $1
`

func (q *Queries) GetGhostBySeed(ctx context.Context, seed string) (GhostRun, error) {
	row := q.db.QueryRow(ctx, getGhostBySeed, seed)
	var i GhostRun
	err := row.Scan(
		&i.Seed,
		&i.GameID,
		&i.ColonyScore,
		&i.EarthScore,
		&i.ReplayJson,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGhost = `-- name: UpsertGhost :one
INSERT INTO ghost_runs (
    seed,
    game_id,
    colony_score,
    earth_score,
    replay_json,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, now()
)
ON CONFLICT (seed) DO UPDATE SET
    game_id = EXCLUDED.game_id,
    colony_score = EXCLUDED.colony_score,
    earth_score = EXCLUDED.earth_score,
    replay_json = EXCLUDED.replay_json,
    updated_at = now()
WHERE ghost_runs.colony_score <= EXCLUDED.colony_score
RETURNING seed, game_id, colony_score, earth_score, replay_json, updated_at
`

type UpsertGhostParams struct {
	Seed        string          `json:"seed"`
	GameID      uuid.UUID       `json:"game_id"`
	ColonyScore int32           `json:"colony_score"`
	EarthScore  int32           `json:"earth_score"`
	ReplayJson  json.RawMessage `json:"replay_json"`
}

func (q *Queries) UpsertGhost(ctx context.Context, arg UpsertGhostParams) (GhostRun, error) {
	row := q.db.QueryRow(ctx, upsertGhost,
		arg.Seed,
		arg.GameID,
		arg.ColonyScore,
		arg.EarthScore,
		arg.ReplayJson,
	)
	var i GhostRun
	err := row.Scan(
		&i.Seed,
		&i.GameID,
		&i.ColonyScore,
		&i.EarthScore,
		&i.ReplayJson,
		&i.UpdatedAt,
	)
	return i, err
}
