// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Contract struct {
	ID          uuid.UUID          `json:"id"`
	GameID      uuid.UUID          `json:"game_id"`
	PayloadJson json.RawMessage    `json:"payload_json"`
	Status      string             `json:"status"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
}

type Game struct {
	ID             uuid.UUID          `json:"id"`
	Seed           string             `json:"seed"`
	Status         string             `json:"status"`
	MapJson        json.RawMessage    `json:"map_json"`
	Crisis         string             `json:"crisis"`
	TerminatorJson json.RawMessage    `json:"terminator_json"`
	ColonyScore    int32              `json:"colony_score"`
	EarthScore     int32              `json:"earth_score"`
	RoverType      string             `json:"rover_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type GameEvent struct {
	ID          int64              `json:"id"`
	GameID      uuid.UUID          `json:"game_id"`
	T           float64            `json:"t"`
	Kind        string             `json:"kind"`
	PayloadJson []byte             `json:"payload_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GhostRun struct {
	Seed        string             `json:"seed"`
	GameID      uuid.UUID          `json:"game_id"`
	ColonyScore int32              `json:"colony_score"`
	EarthScore  int32              `json:"earth_score"`
	ReplayJson  json.RawMessage    `json:"replay_json"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
